//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookieProjects.PuttyLauncher.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookieProjects.PuttyLauncher.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Create_Base {
            get {
                return ResourceManager.GetString("Create_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string Create_Base_Hostname {
            get {
                return ResourceManager.GetString("Create_Base_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Protocol Version.
        /// </summary>
        public static string Create_Base_IPVersion {
            get {
                return ResourceManager.GetString("Create_Base_IPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Create_Base_IPVersion_Auto {
            get {
                return ResourceManager.GetString("Create_Base_IPVersion_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4.
        /// </summary>
        public static string Create_Base_IPVersion_IPv4 {
            get {
                return ResourceManager.GetString("Create_Base_IPVersion_IPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6.
        /// </summary>
        public static string Create_Base_IPVersion_IPv6 {
            get {
                return ResourceManager.GetString("Create_Base_IPVersion_IPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Create_Base_Port {
            get {
                return ResourceManager.GetString("Create_Base_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Create_Base_Username {
            get {
                return ResourceManager.GetString("Create_Base_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string Create_Base_Verbose {
            get {
                return ResourceManager.GetString("Create_Base_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Create_Command {
            get {
                return ResourceManager.GetString("Create_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Create_Command_Description {
            get {
                return ResourceManager.GetString("Create_Command_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Create_Command_Name {
            get {
                return ResourceManager.GetString("Create_Command_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        public static string Create_Protocol {
            get {
                return ResourceManager.GetString("Create_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        public static string Create_Protocol_Raw {
            get {
                return ResourceManager.GetString("Create_Protocol_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rlogin.
        /// </summary>
        public static string Create_Protocol_Rlogin {
            get {
                return ResourceManager.GetString("Create_Protocol_Rlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Create_Protocol_Serial {
            get {
                return ResourceManager.GetString("Create_Protocol_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH.
        /// </summary>
        public static string Create_Protocol_SSH {
            get {
                return ResourceManager.GetString("Create_Protocol_SSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telnet.
        /// </summary>
        public static string Create_Protocol_Telnet {
            get {
                return ResourceManager.GetString("Create_Protocol_Telnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Create_Serial {
            get {
                return ResourceManager.GetString("Create_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        public static string Create_Serial_BaudRate {
            get {
                return ResourceManager.GetString("Create_Serial_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Bits.
        /// </summary>
        public static string Create_Serial_DataBits {
            get {
                return ResourceManager.GetString("Create_Serial_DataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Control.
        /// </summary>
        public static string Create_Serial_FlowControl {
            get {
                return ResourceManager.GetString("Create_Serial_FlowControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSR/DTS.
        /// </summary>
        public static string Create_Serial_FlowControl_DSR_DTR {
            get {
                return ResourceManager.GetString("Create_Serial_FlowControl_DSR_DTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Create_Serial_FlowControl_None {
            get {
                return ResourceManager.GetString("Create_Serial_FlowControl_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTS/CTS.
        /// </summary>
        public static string Create_Serial_FlowControl_RTS_CTS {
            get {
                return ResourceManager.GetString("Create_Serial_FlowControl_RTS_CTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XON/XOFF.
        /// </summary>
        public static string Create_Serial_FlowControl_XON_XOFF {
            get {
                return ResourceManager.GetString("Create_Serial_FlowControl_XON_XOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string Create_Serial_Parity {
            get {
                return ResourceManager.GetString("Create_Serial_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even.
        /// </summary>
        public static string Create_Serial_Parity_Even {
            get {
                return ResourceManager.GetString("Create_Serial_Parity_Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Create_Serial_Parity_Mark {
            get {
                return ResourceManager.GetString("Create_Serial_Parity_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Create_Serial_Parity_None {
            get {
                return ResourceManager.GetString("Create_Serial_Parity_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd.
        /// </summary>
        public static string Create_Serial_Parity_Odd {
            get {
                return ResourceManager.GetString("Create_Serial_Parity_Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Create_Serial_Parity_Space {
            get {
                return ResourceManager.GetString("Create_Serial_Parity_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Line.
        /// </summary>
        public static string Create_Serial_SerialLine {
            get {
                return ResourceManager.GetString("Create_Serial_SerialLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bits.
        /// </summary>
        public static string Create_Serial_StopBits {
            get {
                return ResourceManager.GetString("Create_Serial_StopBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH.
        /// </summary>
        public static string Create_SSH {
            get {
                return ResourceManager.GetString("Create_SSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Agent.
        /// </summary>
        public static string Create_SSH_ForwardAgent {
            get {
                return ResourceManager.GetString("Create_SSH_ForwardAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Create_SSH_OpenPrivateKey {
            get {
                return ResourceManager.GetString("Create_SSH_OpenPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key.
        /// </summary>
        public static string Create_SSH_PrivateKey {
            get {
                return ResourceManager.GetString("Create_SSH_PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between 5 and 9..
        /// </summary>
        public static string Exception_Serial_DataBits_OutOfRange {
            get {
                return ResourceManager.GetString("Exception_Serial_DataBits_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be 1, 1.5 or 2..
        /// </summary>
        public static string Exception_Serial_StopBits_OutOfRange {
            get {
                return ResourceManager.GetString("Exception_Serial_StopBits_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads all private keys that are registered to your sessions..
        /// </summary>
        public static string LoadPrivateKeys_Description {
            get {
                return ResourceManager.GetString("LoadPrivateKeys_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PuTTY: Load private keys.
        /// </summary>
        public static string LoadPrivateKeys_Name {
            get {
                return ResourceManager.GetString("LoadPrivateKeys_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically loads all your putty sessions and creates a launcher for them..
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch PuTTY session {{session}}..
        /// </summary>
        public static string PuttyLauncher_Description {
            get {
                return ResourceManager.GetString("PuttyLauncher_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PuTTY: {{session}}.
        /// </summary>
        public static string PuttyLauncher_Name {
            get {
                return ResourceManager.GetString("PuttyLauncher_Name", resourceCulture);
            }
        }
    }
}
